version: "3"
services:
  client:
    container_name: docker-client
    restart: always
    build: ./e-sante
    ports:
      - '8080:3000'
  app:
    container_name: docker-api
    restart: always
    build: ./esante-backend
    ports:
      - '9000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'